### ISSUE TITLE
Erstellen der KNX Produktdatenbank

### ISSUE THREAD

**Issue by michaelkusolitsch** [OpenKNX/OAM-IP-Router#14]
Beim Erstellen der KNX Datenbank mit openknxproducer bekomme ich immer eine Fehlermeldung

```
> OpenKNXproducer.exe create --Debug -h "knxprod.h" "src/IP-Router.xml" 

OpenKNXproducer 3.3.4.0
Processing xml file src/IP-Router.xml
Processing include src/IP-Router.xml
Processing include ../lib/OGM-Common/src/Common.share.xml
Processing include Common.script.js
Processing include ../lib/OFM-Network/src/Network.share.xml
Processing include IP-Router.share.xml
Processing include ../lib/OGM-Common/src/Common.Router.share.xml
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at ExtendedEtsSupport.GenerateScriptContent(ProcessInclude iInclude, DefineContent iDefine)
   at OpenKNXproducer.ProcessInclude.ResolveIncludes(String iCurrentDir)
   at OpenKNXproducer.ProcessInclude.LoadAdvanced(String iFileName)
   at OpenKNXproducer.ProcessInclude.Expand()
   at OpenKNXproducer.Program.VerbCreate(CreateOptions opts)
   at OpenKNXproducer.Program.<>c.<Main>b__32_2(CreateOptions opts)
   at CommandLine.ParserResultExtensions.MapResult[T1,T2,T3,T4,T5,TResult](ParserResult`1 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 parsedFunc3, Func`2 parsedFunc4, Func`2 parsedFunc5, Func`2 
notParsedFunc)
   at OpenKNXproducer.Program.Main(String[] args)
``` 

Habe in den Files noch nichts geändert.
Hoffe mir kann jemand dabei helfen

**Comment by Ing-Dom** [comment]
sind die dependencies vorhanden?
https://github.com/OpenKNX/OpenKNX/wiki/Information-for-Developers

**Comment by michaelkusolitsch** [comment]
ja sind alle vorhanden - die firmware lässt sich ohne probleme kompilieren nur eben nicht die Produktdatenbank "IP-Router.xml" (Die Debug Versionen funktionieren, wenn die entsprechenden Baggages in den Ordner kopiert werden - Aus dem Release mit den Prebuild)

**Comment by Ing-Dom** [comment]
welcher branch?

**Comment by michaelkusolitsch** [comment]
main branch

**Comment by Ing-Dom** [comment]
das liegt dann sicher daran dass die dependencies sich mitlerweile weiterentwickelt haben.
Also entweder https://github.com/OpenKNX/OAM-IP-Router/releases/tag/0.1.3 verwenden

ist diese Datei vorhanden ?
Processing include ../lib/OGM-Common/src/Common.Router.share.xml

**Comment by michaelkusolitsch** [comment]
ja das File existiert. Ich habe jetzt zu 0.1.3 gewechselt und die Dependencies wie in der Wiki neu geladen. Ich bekomme jedoch den selben Fehler.

**Comment by Ing-Dom** [comment]
ich meinte das zip im release
https://github.com/OpenKNX/OAM-IP-Router/releases/download/0.1.3/IP-Router-Release-0.1.3.zip

das muss gehen.

**Comment by Ing-Dom** [comment]
es gab da eine Umstellung im producer, mit dem 3.3.4.0 läuft die Erstellung der 0.1.3 aus den sourcen nicht mehr. Das Release klappt aber.
aktueller baufähiger workbranch ist v0_2_lwip
